/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dqkhanh
 */
public class Garage extends javax.swing.JFrame {

    /**
     * Creates new form Garage
     */
    public Garage() {
        initComponents();
        Toolkit toolKit = getToolkit();
        Dimension size = toolKit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        jToggleButton53 = new javax.swing.JToggleButton();
        jToggleButton54 = new javax.swing.JToggleButton();
        jToggleButton55 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jToggleButton60 = new javax.swing.JToggleButton();
        jToggleButton61 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton63 = new javax.swing.JToggleButton();
        jToggleButton64 = new javax.swing.JToggleButton();
        jToggleButton65 = new javax.swing.JToggleButton();
        jToggleButton66 = new javax.swing.JToggleButton();
        jToggleButton67 = new javax.swing.JToggleButton();
        jToggleButton68 = new javax.swing.JToggleButton();
        jToggleButton69 = new javax.swing.JToggleButton();
        jToggleButton70 = new javax.swing.JToggleButton();
        jToggleButton71 = new javax.swing.JToggleButton();
        jToggleButton72 = new javax.swing.JToggleButton();
        jToggleButton73 = new javax.swing.JToggleButton();
        jToggleButton74 = new javax.swing.JToggleButton();
        jToggleButton75 = new javax.swing.JToggleButton();
        jToggleButton76 = new javax.swing.JToggleButton();
        jToggleButton77 = new javax.swing.JToggleButton();
        jToggleButton78 = new javax.swing.JToggleButton();
        jToggleButton79 = new javax.swing.JToggleButton();
        jToggleButton80 = new javax.swing.JToggleButton();
        jToggleButton81 = new javax.swing.JToggleButton();
        jToggleButton82 = new javax.swing.JToggleButton();
        jToggleButton83 = new javax.swing.JToggleButton();
        jToggleButton84 = new javax.swing.JToggleButton();
        jToggleButton85 = new javax.swing.JToggleButton();
        jToggleButton86 = new javax.swing.JToggleButton();
        jToggleButton87 = new javax.swing.JToggleButton();
        jToggleButton88 = new javax.swing.JToggleButton();
        jToggleButton89 = new javax.swing.JToggleButton();
        jToggleButton90 = new javax.swing.JToggleButton();
        jToggleButton91 = new javax.swing.JToggleButton();
        jToggleButton92 = new javax.swing.JToggleButton();
        jToggleButton93 = new javax.swing.JToggleButton();
        jToggleButton94 = new javax.swing.JToggleButton();
        jToggleButton95 = new javax.swing.JToggleButton();
        jToggleButton96 = new javax.swing.JToggleButton();
        jToggleButton97 = new javax.swing.JToggleButton();
        jToggleButton98 = new javax.swing.JToggleButton();
        jToggleButton99 = new javax.swing.JToggleButton();
        jToggleButton100 = new javax.swing.JToggleButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Garage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(539, 539, 539)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jToggleButton1.setText("Slot 1");
        jToggleButton1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jToggleButton2.setText("Slot 2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Slot 3");

        jToggleButton4.setText("Slot 4");

        jToggleButton5.setText("Slot 5");

        jToggleButton6.setText("Slot 6");

        jToggleButton7.setText("Slot 7");

        jToggleButton8.setText("Slot 8");

        jToggleButton9.setText("Slot 9");

        jToggleButton10.setText("Slot 10");

        jToggleButton11.setText("Slot 11");

        jToggleButton12.setText("Slot 12");

        jToggleButton13.setText("Slot 13");

        jToggleButton14.setText("Slot 14");

        jToggleButton15.setText("Slot 15");

        jToggleButton16.setText("Slot 16");

        jToggleButton17.setText("Slot 17");

        jToggleButton18.setText("Slot 18");

        jToggleButton19.setText("Slot 19");

        jToggleButton20.setText("Slot 20");

        jToggleButton21.setText("Slot 21");

        jToggleButton22.setText("Slot 22");

        jToggleButton24.setText("Slot 24");
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });

        jToggleButton25.setText("Slot 25");

        jToggleButton26.setText("Slot 26");

        jToggleButton27.setText("Slot 27");

        jToggleButton28.setText("Slot 28");

        jToggleButton29.setText("Slot 29");

        jToggleButton30.setText("Slot 30");

        jToggleButton31.setText("Slot 31");
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });

        jToggleButton32.setText("Slot 32");
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });

        jToggleButton23.setText("Slot 23");

        jToggleButton33.setText("Slot 33");

        jToggleButton34.setText("Slot 34");

        jToggleButton35.setText("Slot 35");

        jToggleButton36.setText("Slot 36");

        jToggleButton37.setText("Slot 37");

        jToggleButton38.setText("Slot 38");

        jToggleButton39.setText("Slot 39");

        jToggleButton40.setText("Slot 40");

        jToggleButton41.setText("Slot 41");

        jToggleButton42.setText("Slot 42");

        jToggleButton43.setText("Slot 43");

        jToggleButton44.setText("Slot 44");

        jToggleButton45.setText("Slot 45");

        jToggleButton46.setText("Slot 46");

        jToggleButton47.setText("Slot 47");

        jToggleButton48.setText("Slot 48");

        jToggleButton49.setText("Slot 49");

        jToggleButton50.setText("Slot 50");

        jToggleButton51.setText("Slot 51");

        jToggleButton52.setText("Slot 52");

        jToggleButton53.setText("Slot 53");

        jToggleButton54.setText("Slot 54");

        jToggleButton55.setText("Slot 55");

        jToggleButton56.setText("Slot 56");

        jToggleButton57.setText("Slot 57");

        jToggleButton58.setText("Slot 58");

        jToggleButton59.setText("Slot 59");

        jToggleButton60.setText("Slot 60");

        jToggleButton61.setText("Slot 61");

        jToggleButton62.setText("Slot 62");

        jToggleButton63.setText("Slot 63");

        jToggleButton64.setText("Slot 64");

        jToggleButton65.setText("Slot 65");

        jToggleButton66.setText("Slot 66");

        jToggleButton67.setText("Slot 67");

        jToggleButton68.setText("Slot 68");

        jToggleButton69.setText("Slot 69");

        jToggleButton70.setText("Slot 70");

        jToggleButton71.setText("Slot 71");

        jToggleButton72.setText("Slot 72");

        jToggleButton73.setText("Slot 73");

        jToggleButton74.setText("Slot 74");

        jToggleButton75.setText("Slot 75");

        jToggleButton76.setText("Slot 76");

        jToggleButton77.setText("Slot 77");
        jToggleButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton77ActionPerformed(evt);
            }
        });

        jToggleButton78.setText("Slot 78");

        jToggleButton79.setText("Slot 79");

        jToggleButton80.setText("Slot 80");
        jToggleButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton80ActionPerformed(evt);
            }
        });

        jToggleButton81.setText("Slot 81");

        jToggleButton82.setText("Slot 82");

        jToggleButton83.setText("Slot 83");

        jToggleButton84.setText("Slot 84");

        jToggleButton85.setText("Slot 85");

        jToggleButton86.setText("Slot 86");
        jToggleButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton86ActionPerformed(evt);
            }
        });

        jToggleButton87.setText("Slot 87");

        jToggleButton88.setText("Slot 88");
        jToggleButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton88ActionPerformed(evt);
            }
        });

        jToggleButton89.setText("Slot 89");
        jToggleButton89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton89ActionPerformed(evt);
            }
        });

        jToggleButton90.setText("Slot 90");

        jToggleButton91.setText("Slot 91");

        jToggleButton92.setText("Slot 92");

        jToggleButton93.setText("Slot 93");

        jToggleButton94.setText("Slot 94");
        jToggleButton94.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton94ActionPerformed(evt);
            }
        });

        jToggleButton95.setText("Slot 95");

        jToggleButton96.setText("Slot 96");
        jToggleButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton96ActionPerformed(evt);
            }
        });

        jToggleButton97.setText("Slot 97");

        jToggleButton98.setText("Slot 98");
        jToggleButton98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton98ActionPerformed(evt);
            }
        });

        jToggleButton99.setText("Slot 99");
        jToggleButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton99ActionPerformed(evt);
            }
        });

        jToggleButton100.setText("Slot 100");

        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(1113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton91)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton92)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton93)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton94)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton95)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton96)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton97)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton98)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton99)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton100))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton71)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton72)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton73)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton74)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton75)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton76)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton77)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton78)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton79)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton80))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton61)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton62)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton63)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton64)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton65)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton66)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton67)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton68)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton69)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton51)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton52)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton53)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton54)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton55)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton56)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton57)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton58)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton59)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton41)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton42)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton43)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton44)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton45)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton46)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton47)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton48)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton49)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton31)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton32)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton33)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton34)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton35)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton36)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton37)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton38)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton39)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jToggleButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jToggleButton12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jToggleButton13))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton21)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButton23)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton24)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton25)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton26)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton27)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton28)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton29)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToggleButton14)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton15)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton16)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton17)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton18)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton19)
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButton81)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton82)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton83)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton84)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton85)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton86)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton87)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton88)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton89)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButton90)))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton16)
                    .addComponent(jToggleButton17)
                    .addComponent(jToggleButton18)
                    .addComponent(jToggleButton19)
                    .addComponent(jToggleButton20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton21)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton24)
                    .addComponent(jToggleButton25)
                    .addComponent(jToggleButton26)
                    .addComponent(jToggleButton27)
                    .addComponent(jToggleButton28)
                    .addComponent(jToggleButton29)
                    .addComponent(jToggleButton30)
                    .addComponent(jToggleButton23))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton32)
                    .addComponent(jToggleButton33)
                    .addComponent(jToggleButton34)
                    .addComponent(jToggleButton35)
                    .addComponent(jToggleButton36)
                    .addComponent(jToggleButton37)
                    .addComponent(jToggleButton38)
                    .addComponent(jToggleButton39)
                    .addComponent(jToggleButton40)
                    .addComponent(jToggleButton31))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton41)
                    .addComponent(jToggleButton42)
                    .addComponent(jToggleButton43)
                    .addComponent(jToggleButton44)
                    .addComponent(jToggleButton45)
                    .addComponent(jToggleButton46)
                    .addComponent(jToggleButton47)
                    .addComponent(jToggleButton48)
                    .addComponent(jToggleButton49)
                    .addComponent(jToggleButton50))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton51)
                    .addComponent(jToggleButton52)
                    .addComponent(jToggleButton53)
                    .addComponent(jToggleButton54)
                    .addComponent(jToggleButton55)
                    .addComponent(jToggleButton56)
                    .addComponent(jToggleButton57)
                    .addComponent(jToggleButton58)
                    .addComponent(jToggleButton59)
                    .addComponent(jToggleButton60))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton61)
                    .addComponent(jToggleButton62)
                    .addComponent(jToggleButton63)
                    .addComponent(jToggleButton64)
                    .addComponent(jToggleButton65)
                    .addComponent(jToggleButton66)
                    .addComponent(jToggleButton67)
                    .addComponent(jToggleButton68)
                    .addComponent(jToggleButton69)
                    .addComponent(jToggleButton70))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton71)
                    .addComponent(jToggleButton72)
                    .addComponent(jToggleButton73)
                    .addComponent(jToggleButton74)
                    .addComponent(jToggleButton75)
                    .addComponent(jToggleButton76)
                    .addComponent(jToggleButton77)
                    .addComponent(jToggleButton78)
                    .addComponent(jToggleButton79)
                    .addComponent(jToggleButton80))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton81)
                    .addComponent(jToggleButton82)
                    .addComponent(jToggleButton83)
                    .addComponent(jToggleButton84)
                    .addComponent(jToggleButton85)
                    .addComponent(jToggleButton86)
                    .addComponent(jToggleButton87)
                    .addComponent(jToggleButton88)
                    .addComponent(jToggleButton89)
                    .addComponent(jToggleButton90))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton91)
                    .addComponent(jToggleButton92)
                    .addComponent(jToggleButton93)
                    .addComponent(jToggleButton94)
                    .addComponent(jToggleButton95)
                    .addComponent(jToggleButton96)
                    .addComponent(jToggleButton97)
                    .addComponent(jToggleButton98)
                    .addComponent(jToggleButton99)
                    .addComponent(jToggleButton100))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton77ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton77ActionPerformed

    private void jToggleButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton80ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton80ActionPerformed

    private void jToggleButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton86ActionPerformed

    private void jToggleButton89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton89ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton89ActionPerformed

    private void jToggleButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton88ActionPerformed

    private void jToggleButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton96ActionPerformed

    private void jToggleButton98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton98ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton98ActionPerformed

    private void jToggleButton99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton99ActionPerformed

    private void jToggleButton94ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton94ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton94ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        try {
            new Admin().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Garage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Garage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton100;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton53;
    private javax.swing.JToggleButton jToggleButton54;
    private javax.swing.JToggleButton jToggleButton55;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton60;
    private javax.swing.JToggleButton jToggleButton61;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton63;
    private javax.swing.JToggleButton jToggleButton64;
    private javax.swing.JToggleButton jToggleButton65;
    private javax.swing.JToggleButton jToggleButton66;
    private javax.swing.JToggleButton jToggleButton67;
    private javax.swing.JToggleButton jToggleButton68;
    private javax.swing.JToggleButton jToggleButton69;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton70;
    private javax.swing.JToggleButton jToggleButton71;
    private javax.swing.JToggleButton jToggleButton72;
    private javax.swing.JToggleButton jToggleButton73;
    private javax.swing.JToggleButton jToggleButton74;
    private javax.swing.JToggleButton jToggleButton75;
    private javax.swing.JToggleButton jToggleButton76;
    private javax.swing.JToggleButton jToggleButton77;
    private javax.swing.JToggleButton jToggleButton78;
    private javax.swing.JToggleButton jToggleButton79;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton80;
    private javax.swing.JToggleButton jToggleButton81;
    private javax.swing.JToggleButton jToggleButton82;
    private javax.swing.JToggleButton jToggleButton83;
    private javax.swing.JToggleButton jToggleButton84;
    private javax.swing.JToggleButton jToggleButton85;
    private javax.swing.JToggleButton jToggleButton86;
    private javax.swing.JToggleButton jToggleButton87;
    private javax.swing.JToggleButton jToggleButton88;
    private javax.swing.JToggleButton jToggleButton89;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JToggleButton jToggleButton90;
    private javax.swing.JToggleButton jToggleButton91;
    private javax.swing.JToggleButton jToggleButton92;
    private javax.swing.JToggleButton jToggleButton93;
    private javax.swing.JToggleButton jToggleButton94;
    private javax.swing.JToggleButton jToggleButton95;
    private javax.swing.JToggleButton jToggleButton96;
    private javax.swing.JToggleButton jToggleButton97;
    private javax.swing.JToggleButton jToggleButton98;
    private javax.swing.JToggleButton jToggleButton99;
    // End of variables declaration//GEN-END:variables
}
